
set(FILES
    Include/xXGameProjectNameXx/xXGameProjectNameXxBus.h
    Include/xXGameProjectNameXx/xXGameProjectNameXxTypeIds.h
    Source/xXGameProjectNameXxSystemComponent.cpp
    Source/xXGameProjectNameXxSystemComponent.h
    Include/xXGameProjectNameXx/MyExperimentInterface.h
    Source/Components/MyExperimentComponent.h
    Source/Components/MyExperimentComponent.cpp
    Include/xXGameProjectNameXx/MoverInputInterface.h
    Source/Components/MoverInputComponent.h
    Source/Components/MoverInputComponent.cpp
    Include/xXGameProjectNameXx/InputEventNames.h
    Source/Components/ClientMoverInputInjectorComponent.h
    Source/Components/ClientMoverInputInjectorComponent.cpp
    Source/Components/StageSelectComponent.h
    Source/Components/StageSelectComponent.cpp
    Source/GameStates/StageSelect.h
    Source/GameStates/StageSelect.cpp
    Include/xXGameProjectNameXx/SettingsRegistryAccessors.h
    Source/SettingsRegistryAccessors.cpp
    Source/Utils/MultiplayerUtils.h
    Source/Utils/MultiplayerUtils.cpp
)
